/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Submission = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Order = IDL.Record({
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'address' : IDL.Text,
  'city' : IDL.Text,
  'pincode' : IDL.Text,
  'quantity' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Order = IDL.Record({
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'address' : IDL.Text,
    'city' : IDL.Text,
    'pincode' : IDL.Text,
    'quantity' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });

  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
